# Descision Tree classification with countries of the world

In [ ]:
#I will be using the countries of the world dataset to try to predict in which region a particular country lies.
#I will be using the decision tree classifier for this as I will only be using a few simple factors.

In [7]:
#Dependancies
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt


In [141]:
data = pd.read_csv('countries of the world.csv', decimal=",")
data = data.dropna() #Cleaning the data by removing NaN values.
data.reset_index(inplace=True) #Resetting the index after removing rows.
print(data.head())

   index             Country                               Region  Population  \
0      0        Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1      1            Albania   EASTERN EUROPE                          3581655   
2      2            Algeria   NORTHERN AFRICA                        32930091   
3      6           Anguilla               LATIN AMER. & CARIB           13477   
4      7  Antigua & Barbuda               LATIN AMER. & CARIB           69108   

   Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
0          647500                        48.0                          0.00   
1           28748                       124.6                          1.26   
2         2381740                        13.8                          0.04   
3             102                       132.1                         59.80   
4             443                       156.0                         34.54   

   Net migration  Infant mortality (pe

In [142]:
#Extracting only the columns which will be used for prediction, these are the factors I would consider to be most informative.
data = data[['index', 'Country', 'Region', 'Pop. Density (per sq. mi.)', 'GDP ($ per capita)', 'Climate', 'Birthrate']]
print(data.head())

   index             Country                               Region  \
0      0        Afghanistan         ASIA (EX. NEAR EAST)            
1      1            Albania   EASTERN EUROPE                        
2      2            Algeria   NORTHERN AFRICA                       
3      6           Anguilla               LATIN AMER. & CARIB       
4      7  Antigua & Barbuda               LATIN AMER. & CARIB       

   Pop. Density (per sq. mi.)  GDP ($ per capita)  Climate  Birthrate  
0                        48.0               700.0      1.0      46.60  
1                       124.6              4500.0      3.0      15.11  
2                        13.8              6000.0      1.0      17.14  
3                       132.1              8600.0      2.0      14.17  
4                       156.0             11000.0      2.0      16.93  


In [143]:
y = data[['Region']] #Target.
X = data.drop(['Country', 'Region'],1) #Removing these strings so we can apply the model.
y

Region
0          ASIA (EX. NEAR EAST)         
1    EASTERN EUROPE                     
2    NORTHERN AFRICA                    
3                LATIN AMER. & CARIB    
4                LATIN AMER. & CARIB    
..                                   ...
174              LATIN AMER. & CARIB    
175        ASIA (EX. NEAR EAST)         
176  NEAR EAST                          
177  SUB-SAHARAN AFRICA                 
178  SUB-SAHARAN AFRICA                 

[179 rows x 1 columns]

In [144]:
#Our target variable is full of strings, so just like with the iris dataset we will have to convert these to numerical values.
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)
y

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 0,  3,  6,  4,  4,  4,  2,  4,  8, 10,  2,  4,  5,  0,  4,  2, 10,
        4,  9,  7,  0,  4,  9,  4,  4,  0,  3,  9,  0,  9,  0,  9,  9,  4,
        9,  9,  4,  0,  4,  9,  9,  9,  4,  9,  4,  3, 10,  9,  4,  4,  4,
        6,  4,  9,  9,  1,  9,  8, 10, 10,  4,  8,  9,  9,  2, 10,  9, 10,
        4,  4,  4,  9,  9,  4,  4,  4,  0,  3, 10,  0,  0,  0,  5, 10,  5,
        4,  0,  5,  2,  9,  0,  0,  5,  2,  0,  1,  9,  9, 10,  0,  9,  9,
        0,  0,  9,  8,  4,  9,  9,  4,  8,  0,  9,  9, 10,  4,  8,  8,  4,
        9,  9, 10,  5,  0,  8,  4,  8,  4,  4,  0,  3, 10,  4,  5,  9,  3,
        9,  4,  4,  4,  8,  9,  5,  9,  9,  9,  0,  9,  9, 10,  0,  9,  4,
        9, 10, 10,  5,  0,  2,  0,  9,  8,  4,  6,  5,  2,  9,  2,  5, 10,
        7,  4,  2,  8,  4,  0,  5,  9,  9])

In [153]:
#So each of the values 0-10 represents a different region.
#Time to split the data as per usual.
X_train, X_test, y_train,  y_test = train_test_split(X, y, test_size = 0.2)

In [154]:
#Importing and fitting the model.
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [155]:
#Lets take a look at our predictions.
y_pred = clf.predict(X_test)
y_pred

array([10,  9,  5,  2, 10,  4,  4,  9,  9,  9,  9,  9,  0,  9, 10,  4,  4,
       10,  9,  0, 10,  0, 10,  4,  4,  9,  4,  0,  4, 10,  2,  0,  9,  3,
        3,  9])

In [156]:
#Accuracy:
accuracy = accuracy_score(y_pred, y_test)
accuracy

0.5277777777777778

In [ ]:
#This is not great, but not totally useless cosidering there are 11 different classes, lets try another classifier.

In [85]:
from sklearn.neighbors import KNeighborsClassifier

#For simplicity we will start with K=1.
knn_1 = KNeighborsClassifier(n_neighbors = 1)
knn_1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [86]:
y_pred_knn_1 = knn_1.predict(X_test)
y_pred_knn_1

array([ 0,  6,  4,  9,  5,  5,  4,  4,  0,  4,  2,  0,  6, 10,  9,  9,  0,
        9,  0,  9,  8, 10,  8,  9,  0,  6,  9,  9,  9,  0,  0,  4,  0,  9,
        6,  9])

In [87]:
accuracy = accuracy_score(y_pred_knn_1, y_test)
accuracy

0.3055555555555556

In [88]:
#lets try k = 5 now.
knn_5 = KNeighborsClassifier(n_neighbors = 5)
knn_5.fit(X_train, y_train)

y_pred_knn_5 = knn_5.predict(X_test)
y_pred_knn_5

accuracy = accuracy_score(y_pred_knn_5, y_test)
accuracy

0.2222222222222222

In [90]:
#Its getting worse, try k=10 just to confirm.
knn_10 = KNeighborsClassifier(n_neighbors = 10)
knn_10.fit(X_train, y_train)

y_pred_knn_10 = knn_10.predict(X_test)
y_pred_knn_10

accuracy = accuracy_score(y_pred_knn_10, y_test)
accuracy

0.3055555555555556

In [104]:
#KNN is clearly worse, try another type of classifier.

Empty DataFrame
Columns: [Region]
Index: []

In [ ]:
for i in range(len(data)):
    if y[i]

In [102]:
type(y)

pandas.core.frame.DataFrame

In [107]:
y[0]

0